#!/bin/bash
set -euo pipefail

# cursor-insights installer
# Copies hook scripts, merges hooks.json, and optionally sets up Phoenix.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HOOKS_DIR="$HOME/.cursor/hooks"
HOOKS_JSON="$HOME/.cursor/hooks.json"
ENV_FILE="$HOOKS_DIR/.cursor-insights.env"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
err()   { echo -e "${RED}✗${NC} $*"; }
header(){ echo -e "\n${BOLD}$*${NC}"; }

# ── Prerequisites ──────────────────────────────────────────────────────────────

header "Checking prerequisites…"

if ! command -v uv &>/dev/null; then
    warn "uv is required but not found."
    read -rp "  Install uv now? [Y/n]: " install_uv
    install_uv="${install_uv:-Y}"
    if [[ "$install_uv" =~ ^[Yy] ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        if ! command -v uv &>/dev/null; then
            err "uv installation succeeded but is not on PATH."
            echo "  Add ~/.local/bin to your PATH, then re-run this installer."
            exit 1
        fi
        info "uv installed — $(uv --version 2>/dev/null)"
    else
        err "uv is required. Install manually: curl -LsSf https://astral.sh/uv/install.sh | sh"
        exit 1
    fi
else
    info "uv $(uv --version 2>/dev/null || echo '(found)')"
fi

HAS_DOCKER=false
if command -v docker &>/dev/null; then
    HAS_DOCKER=true
    info "docker found"
else
    warn "docker not found (only needed for local Phoenix)"
fi

# ── Copy hook scripts ──────────────────────────────────────────────────────────

header "Installing hook scripts…"

mkdir -p "$HOOKS_DIR"
cp "$SCRIPT_DIR/hooks/trace-hook.sh" "$HOOKS_DIR/trace-hook.sh"
chmod +x "$HOOKS_DIR/trace-hook.sh"
cp "$SCRIPT_DIR/hooks/flush.py" "$HOOKS_DIR/flush.py"
info "Copied trace-hook.sh and flush.py to $HOOKS_DIR"

# ── Merge hooks.json ──────────────────────────────────────────────────────────

header "Configuring Cursor hooks…"

python3 -c "
import json, sys, os

template_path = sys.argv[1]
target_path = sys.argv[2]

with open(template_path) as f:
    template = json.load(f)

target = {'version': 1, 'hooks': {}}
if os.path.exists(target_path):
    with open(target_path) as f:
        target = json.load(f)

for event, commands in template.get('hooks', {}).items():
    existing = target.setdefault('hooks', {}).setdefault(event, [])
    existing_cmds = {c.get('command') for c in existing}
    for cmd in commands:
        if cmd.get('command') not in existing_cmds:
            existing.append(cmd)

with open(target_path, 'w') as f:
    json.dump(target, f, indent=2)
    f.write('\n')
" "$SCRIPT_DIR/hooks.json" "$HOOKS_JSON"

info "Merged hook entries into $HOOKS_JSON"

# ── Phoenix setup ──────────────────────────────────────────────────────────────

header "Phoenix setup"
echo ""
echo "  cursor-insights sends traces to a Phoenix instance."
echo "  How would you like to set up Phoenix?"
echo ""
echo "  1) Local Docker  — spin up Phoenix v13.15.0 in a container"
echo "  2) Existing URL   — connect to a running Phoenix instance"
echo "  3) Skip           — I'll configure this later"
echo ""

PHOENIX_HOST="http://localhost:6006"
PHOENIX_SETUP="skip"

read -rp "  Choose [1/2/3] (default: 1): " phoenix_choice
phoenix_choice="${phoenix_choice:-1}"

case "$phoenix_choice" in
    1)
        PHOENIX_SETUP="docker"
        if [ "$HAS_DOCKER" = false ]; then
            err "Docker is required for local setup but not installed."
            echo "  Install Docker Desktop: https://www.docker.com/products/docker-desktop"
            echo "  Then re-run this installer, or choose option 2/3."
            exit 1
        fi
        PHOENIX_HOST="http://localhost:6006"
        ;;
    2)
        PHOENIX_SETUP="remote"
        read -rp "  Phoenix URL (e.g. https://phoenix.mycompany.com): " user_url
        if [ -z "$user_url" ]; then
            err "URL cannot be empty."
            exit 1
        fi
        PHOENIX_HOST="$user_url"
        ;;
    3)
        PHOENIX_SETUP="skip"
        warn "Skipping Phoenix setup. Set PHOENIX_HOST in $ENV_FILE later."
        ;;
    *)
        err "Invalid choice. Please run the installer again."
        exit 1
        ;;
esac

# ── Project name ───────────────────────────────────────────────────────────────

PHOENIX_PROJECT="cursor"
read -rp "  Phoenix project name (default: cursor): " user_project
PHOENIX_PROJECT="${user_project:-cursor}"

# ── Write env file ─────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# cursor-insights configuration
# Generated by install.sh — edit freely.
PHOENIX_HOST="$PHOENIX_HOST"
PHOENIX_PROJECT="$PHOENIX_PROJECT"
# CURSOR_TRACES_DEBUG="true"
# CURSOR_TRACES_SKIP="field1,field2"
# CURSOR_TRACES_BUFFER="/tmp/cursor-traces.jsonl"
EOF

info "Settings saved to $ENV_FILE"

# ── Start local Phoenix ────────────────────────────────────────────────────────

if [ "$PHOENIX_SETUP" = "docker" ]; then
    header "Starting Phoenix…"
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d
    echo ""

    # Wait for Phoenix to become healthy
    for i in $(seq 1 15); do
        if curl -sf "$PHOENIX_HOST" >/dev/null 2>&1; then
            info "Phoenix is running at $PHOENIX_HOST"
            break
        fi
        if [ "$i" -eq 15 ]; then
            warn "Phoenix did not respond in time. Check: docker logs cursor-insights-phoenix"
        fi
        sleep 2
    done
fi

# ── Validate ───────────────────────────────────────────────────────────────────

if [ "$PHOENIX_SETUP" != "skip" ]; then
    if curl -sf "$PHOENIX_HOST" >/dev/null 2>&1; then
        info "Phoenix reachable at $PHOENIX_HOST"
    else
        warn "Could not reach Phoenix at $PHOENIX_HOST — check the URL or start it manually."
    fi
fi

# ── Done ───────────────────────────────────────────────────────────────────────

header "Installation complete!"
echo ""
echo "  Hook scripts:   $HOOKS_DIR/trace-hook.sh"
echo "  Flush script:   $HOOKS_DIR/flush.py"
echo "  Hooks config:   $HOOKS_JSON"
echo "  Settings:       $ENV_FILE"
if [ "$PHOENIX_SETUP" = "docker" ]; then
    echo "  Phoenix UI:     $PHOENIX_HOST"
fi
echo ""
echo "  Cursor will now trace agent sessions automatically."
echo "  Traces flush to Phoenix on session end, or manually:"
echo "    uv run $HOOKS_DIR/flush.py"
echo ""
